server:
  port: 8888

spring:
  application:
    name: lwzhjkpt-web

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

hessian:
  simple:
    userService-URL: http://GEOSHARE-SERVICE/remote


debug: true





